# Generated by Django 4.2 on 2023-05-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('idBrand', models.AutoField(primary_key=True, serialize=False)),
                ('nameBrand', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'home_brand',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('idCar', models.AutoField(primary_key=True, serialize=False)),
                ('nameCar', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=2048)),
                ('year', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=20)),
                ('kmsDriven', models.CharField(max_length=12)),
                ('fuelType', models.CharField(max_length=20)),
                ('idBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSell',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=50)),
                ('nameCar', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=10)),
                ('kmsDriven', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=12)),
                ('OwnerName', models.CharField(max_length=50)),
                ('Accept', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'home_registersell',
            },
        ),
        migrations.CreateModel(
            name='DetailCar',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('advange', models.TextField()),
                ('phoneContact', models.CharField(max_length=11)),
                ('idCar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.car')),
            ],
        ),
    ]
